name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  init:
    runs-on: ubuntu-latest
    name: Init
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Code Build
        run: echo "Building the code"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Unit Tests
        run: echo "Running unit tests"
