name: Laravel Pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Copy .env
        run: 'php -r "file_exists(''.env'') || copy(''.env.example'', ''.env'');"'
      - name: Set environment specific .env variables
        run: |
          echo "APP_ENV=development" >> .env
          echo "DB_DATABASE=database_dev.sqlite" >> .env
      - name: Remove existing vendor directory
        run: rm -rf vendor
      - name: Install Dependencies
        run: >-
          composer install --prefer-dist --no-progress --no-suggest
          --no-interaction --ansi
      - name: Generate key
        run: 'php artisan key:generate'
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database_dev.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database_dev.sqlite
        run: php artisan test
      - name: Print message
        run: 'echo "Hello, DEV environment"'
  test:
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Copy .env
        run: 'php -r "file_exists(''.env'') || copy(''.env.example'', ''.env'');"'
      - name: Set environment specific .env variables
        run: |
          echo "APP_ENV=testing" >> .env
          echo "DB_DATABASE=database_test.sqlite" >> .env
      - name: Remove existing vendor directory
        run: rm -rf vendor
      - name: Install Dependencies
        run: >-
          composer install --prefer-dist --no-progress --no-suggest
          --no-interaction --ansi
      - name: Generate key
        run: 'php artisan key:generate'
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database_test.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database_test.sqlite
        run: php artisan test
      - name: Print message
        run: 'echo "Hello, TEST environment"'
  prod:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Copy .env
        run: 'php -r "file_exists(''.env'') || copy(''.env.example'', ''.env'');"'
      - name: Set environment specific .env variables
        run: |
          echo "APP_ENV=production" >> .env
          echo "DB_DATABASE=database_prod.sqlite" >> .env
      - name: Remove existing vendor directory
        run: rm -rf vendor
      - name: Install Dependencies
        run: >-
          composer install --prefer-dist --no-progress --no-suggest
          --no-interaction --ansi
      - name: Generate key
        run: 'php artisan key:generate'
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database_prod.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database_prod.sqlite
        run: php artisan test
      - name: Print message
        run: 'echo "Hello, PROD environment"'
