name: Simple Environment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, DEV environment"

  test:
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: Print message
        run: echo "Hello, TEST environment"

  prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || needs.test.result == 'success'
    needs: test
    steps:
      - name: Print message
        run: echo "Hello, PROD environment"
