name: Simple Environment Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  init:
    runs-on: "ubuntu-latest"
    name: Init
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4


  scan:
    runs-on: "ubuntu-latest"
    name: Scan
    needs:
     - init
    steps:
     - name: Sonar Scan
       run: echo "this is my build"
     - name: Trivy Scan
       run: echo "this is my build"
  dev:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Print message
        run: echo "Hello, DEV environment"

  test:
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: Print message
        run: echo "Hello, TEST environment"

  prod:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print message
        run: echo "Hello, PROD environment"
