name: Laravel
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - dev
          - test
          - prod
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: 'mbstring, xml, bcmath, gd, pdo_mysql, curl, json'
      - name: Copy .env
        run: 'php -r "file_exists(''.env'') || copy(''.env.example'', ''.env'');"'
      - name: Set environment specific .env variables
        run: |
          if [ "${{ matrix.environment }}" == "dev" ]; then
            echo "APP_ENV=development" >> .env
            echo "DB_DATABASE=database_dev.sqlite" >> .env
          elif [ "${{ matrix.environment }}" == "test" ]; then
            echo "APP_ENV=testing" >> .env
            echo "DB_DATABASE=database_test.sqlite" >> .env
          elif [ "${{ matrix.environment }}" == "prod" ]; then
            echo "APP_ENV=production" >> .env
            echo "DB_DATABASE=database_prod.sqlite" >> .env
          fi
      - name: Remove existing vendor directory
        run: rm -rf vendor
      - name: Install Dependencies
        run: >-
          composer install --prefer-dist --no-progress --no-suggest
          --no-interaction --ansi
      - name: Generate key
        run: 'php artisan key:generate'
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/${{ matrix.environment }}.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: 'database/${{ matrix.environment }}.sqlite'
        run: php artisan test
