name: Simple Environment Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  init:
    runs-on: "ubuntu-latest"
    name: Init
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
     - name: Checkout
       uses: actions/checkout@v4

  build:
   runs-on: "ubuntu-latest"
   name: build
   needs:
   - init
   steps:
    - name: Code Build
      run: echo "this is my build"
  test:
    runs-on: "ubuntu-latest"
    name: test
    needs:
    - build
    steps:
     - name: Unit Test
       run: echo "this is my build"
  scan:
    runs-on: "ubuntu-latest"
    name: scan
    needs:
     - test
    steps:
     - name: Sonar Scan
       run: echo "this is my build"
     - name: Trivy Scan
       run: echo "this is my build"

  Unittest:
    runs-on: ubuntu-latest
    name: Unittest
    needs: scan
    steps:
     - name: Print message
       run: echo "Hello, TEST environment"
  dev:
    runs-on: ubuntu-latest
    needs: Unittest
    steps:
      - name: Print message
        run: echo "Hello, DEV environment"
  prod:
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: Print message
        run: echo "Hello, PROD environment"
