name: Security & Code Scan Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  test:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Run tests
        run: echo "Running test before scan"

  scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Sonar Scan
        run: echo "Running SonarQube scan"
      - name: Trivy Scan
        run: echo "Running Trivy vulnerability scan"
